[project]
name = "banking-service"
version = "1.0.0"
description = "Service handles Customers and Bank accounts CRUD and other operations."
authors = [
    {name="Attila Wind", email="attilaw@swf.technology"}
]
requires-python = ">=3.11"

dependencies = [
    "PyYAML",
    "fastapi[standard]",
    "fastapi-code-generator",
    "structlog",
    "json-log-formatter",
    "prometheus-client"
]

[project.optional-dependencies]
dev = [
    "robotframework",
    "pytest"
]