# generated by fastapi-codegen:
#   filename:  banking-api-v1.yaml
#   timestamp: 2025-01-03T14:09:13+00:00

from __future__ import annotations

from typing import Optional, Union

from fastapi import FastAPI, Header, Path, Query

from src.model.api.generated.common_v1 import MessageResponse
from src.model.api.generated.banking_api_v1 import Customer


app = FastAPI(
    version='1.0',
    title='Banking API',
    description='This API is working with the following business objects:\n * Customer\n * Bank account\n\nIt provides endpoints to manipulate the business objects (RESTful) and execute certain actions (RPC style).\n# Versioning\nAPI follows [Semantic versioning](https://semver.org/) - but no patch versions. You see more info in the README.md file of the folder!\n',
    servers=[
        {'url': 'http://localhost:8080/api', 'description': 'Local dev server'},
        {
            'url': 'https://banking-service.test.ourdomain.com/api',
            'description': 'Our TEST environment',
        },
        {
            'url': 'https://banking-service.ourdomain.com/api',
            'description': 'Our PROD environment',
        },
    ],
)


@app.get(
    '/v1/customers/rest',
    response_model=MessageResponse,
    tags=['Customer management REST API'],
)
def get_v1_customers_rest(
    x_correlationid: Optional[str] = Header(None, alias='x-correlationid'),
    customer_ids: Optional[str] = Query(None, alias='customerIds'),
) -> MessageResponse:
    """
    Query multiple Customers in one-go.
    """
    pass


@app.post(
    '/v1/customers/rest',
    response_model=None,
    responses={
        '201': {'model': MessageResponse},
        '400': {'model': MessageResponse},
        '401': {'model': MessageResponse},
        '403': {'model': MessageResponse},
        '409': {'model': MessageResponse},
    },
    tags=['Customer management REST API'],
)
def post_v1_customers_rest(
    x_correlationid: Optional[str] = Header(None, alias='x-correlationid'),
    body: Customer = None,
) -> Optional[MessageResponse]:
    """
    Creates a new Customer
    """
    pass


@app.get(
    '/v1/customers/rest/{customerId}',
    response_model=Customer,
    responses={
        '401': {'model': MessageResponse},
        '403': {'model': MessageResponse},
        '404': {'model': MessageResponse},
        '409': {'model': MessageResponse},
    },
    tags=['Customer management REST API'],
)
def get_v1_customers_rest_customer_id(
    x_correlationid: Optional[str] = Header(None, alias='x-correlationid'),
    customer_id: str = Path(..., alias='customerId'),
) -> Union[Customer, MessageResponse]:
    """
    To query a specific Customer
    """
    pass


@app.put(
    '/v1/customers/rest/{customerId}',
    response_model=MessageResponse,
    responses={
        '401': {'model': MessageResponse},
        '403': {'model': MessageResponse},
        '404': {'model': MessageResponse},
        '409': {'model': MessageResponse},
    },
    tags=['Customer management REST API'],
)
def put_v1_customers_rest_customer_id(
    x_correlationid: Optional[str] = Header(None, alias='x-correlationid'),
    customer_id: str = Path(..., alias='customerId'),
    body: Customer = None,
) -> MessageResponse:
    """
    To modify a specific Customer
    """
    pass


@app.delete(
    '/v1/customers/rest/{customerId}',
    response_model=MessageResponse,
    responses={
        '401': {'model': MessageResponse},
        '403': {'model': MessageResponse},
        '404': {'model': MessageResponse},
    },
    tags=['Customer management REST API'],
)
def delete_v1_customers_rest_customer_id(
    x_correlationid: Optional[str] = Header(None, alias='x-correlationid'),
    customer_id: str = Path(..., alias='customerId'),
) -> MessageResponse:
    """
    To delete a specific Customer
    """
    pass
