# settings used by the FastAPI app
fast_api:
  http_port: 8080

persistence:
  # if sqlite is used then here is its config
  sqlite:
    # note: you can NOT use literal ":memory:" here - the SqliteDB class is not prepared for this
    # otherwise point to the file
    db_file: local_workfolder/data/sqlite.db
    schema_files:
      # used by SqliteCustomerDAO
      customers:
        - 'db_schemas/sqlite/schema_customer.sql'

metrics:
  is_enabled: true
  port: 9008